# Production Environment Configuration
# Updated: 2025-12-15

# VPC Configuration
vpc:
  id: vpc-0942fedcef7f9ef24
  securityGroupIds:
    - sg-07bef376433a2a342
  subnetIds:
    - subnet-08a7d1fccb72e6083
    - subnet-0b94cb89cf5fd59ae

# Database Configuration
database:
  secretArn: arn:aws:secretsmanager:ap-northeast-1:661103479219:secret:auth-billing-prod/aurora/credentials-tqXdbn
  proxyEndpoint: auth-billing-prod-rds-proxy.proxy-c9q26ou48ccf.ap-northeast-1.rds.amazonaws.com

# Redis Configuration
redis:
  endpoint: master.auth-billing-prod-redis.ytj7dz.apne1.cache.amazonaws.com
  port: 6379

# Cognito Configuration
cognito:
  userPoolId: ap-northeast-1_z76s7mTve
  userPoolArn: arn:aws:cognito-idp:ap-northeast-1:661103479219:userpool/ap-northeast-1_z76s7mTve

# Stripe Configuration
stripe:
  apiKeyArn: arn:aws:secretsmanager:ap-northeast-1:661103479219:secret:auth-billing-prod/stripe/api-key-B5SPVG
  webhookSecretArn: arn:aws:secretsmanager:ap-northeast-1:661103479219:secret:auth-billing-prod/stripe/webhook-secret-d18YWa

# Logging Configuration
logging:
  level: warn

# Lambda Configuration
lambda:
  memorySize: 1024
  timeout: 30
