# Production Environment Configuration
# Updated: 2024-12-14
# TODO: Update values after Terraform apply for production environment

# VPC Configuration
vpc:
  id: vpc-PROD_VPC_ID  # TODO: Update after terraform apply
  securityGroupIds:
    - sg-PROD_LAMBDA_SG_ID  # TODO: Update after terraform apply
  subnetIds:
    - subnet-PROD_PRIVATE_SUBNET_1  # TODO: Update after terraform apply
    - subnet-PROD_PRIVATE_SUBNET_2  # TODO: Update after terraform apply

# Database Configuration
database:
  secretArn: arn:aws:secretsmanager:ap-northeast-1:805673386383:secret:auth-billing-prod/aurora/credentials-XXXXXX
  proxyEndpoint: auth-billing-prod-rds-proxy.proxy-XXXXXX.ap-northeast-1.rds.amazonaws.com

# Redis Configuration
redis:
  endpoint: master.auth-billing-prod-redis.XXXXXX.apne1.cache.amazonaws.com
  port: 6379

# Cognito Configuration
cognito:
  userPoolId: ap-northeast-1_PROD_POOL_ID
  userPoolArn: arn:aws:cognito-idp:ap-northeast-1:805673386383:userpool/ap-northeast-1_PROD_POOL_ID

# Stripe Configuration
stripe:
  apiKeyArn: arn:aws:secretsmanager:ap-northeast-1:805673386383:secret:auth-billing-prod/stripe/api-key-XXXXXX
  webhookSecretArn: arn:aws:secretsmanager:ap-northeast-1:805673386383:secret:auth-billing-prod/stripe/webhook-secret-XXXXXX

# Logging Configuration
logging:
  level: warn

# Lambda Configuration
lambda:
  memorySize: 1024
  timeout: 30
