# ==============================================================================
# GitHub Actions: AWS App Runner Deploy
# ==============================================================================
# App Runner へのデプロイを自動化するワークフロー
# - ECR へのプッシュ
# - App Runner サービスの更新
# ==============================================================================

name: Deploy to App Runner

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AWS_REGION: ap-northeast-1
  # 以下は secrets または vars で設定
  # AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  # ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  # APP_RUNNER_SERVICE_ARN: ${{ vars.APP_RUNNER_SERVICE_ARN }}

jobs:
  # --------------------------------------------------------------------------
  # ビルド & プッシュ
  # --------------------------------------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment
        id: env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}
          tags: |
            type=sha,prefix=${{ steps.env.outputs.environment }}-
            type=raw,value=${{ steps.env.outputs.environment }}-latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ENVIRONMENT=${{ steps.env.outputs.environment }}

  # --------------------------------------------------------------------------
  # App Runner デプロイ
  # --------------------------------------------------------------------------
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    environment:
      name: ${{ needs.build-and-push.outputs.environment || 'dev' }}
      url: ${{ steps.deploy.outputs.service-url }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to App Runner
        id: deploy
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: ${{ vars.APP_RUNNER_SERVICE_NAME }}
          image: ${{ needs.build-and-push.outputs.image-tag }}
          access-role-arn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/apprunner-access-role
          region: ${{ env.AWS_REGION }}
          cpu: 1
          memory: 2
          port: 8080
          wait-for-service-stability-seconds: 300

      - name: Output service URL
        run: |
          echo "Service URL: ${{ steps.deploy.outputs.service-url }}"
          echo "Service ID: ${{ steps.deploy.outputs.service-id }}"

  # --------------------------------------------------------------------------
  # ヘルスチェック
  # --------------------------------------------------------------------------
  health-check:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for service
        run: sleep 30

      - name: Health check
        run: |
          SERVICE_URL="${{ needs.deploy.outputs.service-url }}"
          for i in {1..10}; do
            response=$(curl -s -o /dev/null -w "%{http_code}" "${SERVICE_URL}/health" || true)
            if [ "$response" == "200" ]; then
              echo "Health check passed!"
              exit 0
            fi
            echo "Attempt $i: Got $response, retrying..."
            sleep 10
          done
          echo "Health check failed!"
          exit 1

  # --------------------------------------------------------------------------
  # 通知
  # --------------------------------------------------------------------------
  notify:
    needs: [build-and-push, deploy, health-check]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Slack
        if: vars.SLACK_WEBHOOK_URL != ''
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅' || '❌' }} App Runner Deploy: ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ job.status == 'success' && '✅ Deploy Succeeded' || '❌ Deploy Failed' }}*\n\nRepository: `${{ github.repository }}`\nBranch: `${{ github.ref_name }}`\nCommit: `${{ github.sha }}`"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
